//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchetsPlus {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchetsPlus.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string ActieClear {
            get {
                return ResourceManager.GetString("ActieClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &amp;width.
        /// </summary>
        internal static string ActieKiesDikte {
            get {
                return ResourceManager.GetString("ActieKiesDikte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose &amp;color.
        /// </summary>
        internal static string ActieKiesKleur {
            get {
                return ResourceManager.GetString("ActieKiesKleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;edo.
        /// </summary>
        internal static string ActieRedo {
            get {
                return ResourceManager.GetString("ActieRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Rotate.
        /// </summary>
        internal static string ActieRoteer {
            get {
                return ResourceManager.GetString("ActieRoteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string ActieUndo {
            get {
                return ResourceManager.GetString("ActieUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change &amp;font.
        /// </summary>
        internal static string ActieVeranderFont {
            get {
                return ResourceManager.GetString("ActieVeranderFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap (*.bmp)|*.bmp|JPEG (*.jpg)|*.jpg|PNG (*.png)|*.png.
        /// </summary>
        internal static string ExporterenFilter {
            get {
                return ResourceManager.GetString("ExporterenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xport.
        /// </summary>
        internal static string FileExporteer {
            get {
                return ResourceManager.GetString("FileExporteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string FileNieuw {
            get {
                return ResourceManager.GetString("FileNieuw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string FileOpenen {
            get {
                return ResourceManager.GetString("FileOpenen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string FileOpslaan {
            get {
                return ResourceManager.GetString("FileOpslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;as....
        /// </summary>
        internal static string FileOpslaanAls {
            get {
                return ResourceManager.GetString("FileOpslaanAls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C&amp;lose.
        /// </summary>
        internal static string FileSluiten {
            get {
                return ResourceManager.GetString("FileSluiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error exporting the file!.
        /// </summary>
        internal static string FoutExporterenTekst {
            get {
                return ResourceManager.GetString("FoutExporterenTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error openening this file!.
        /// </summary>
        internal static string FoutOpenenTekst {
            get {
                return ResourceManager.GetString("FoutOpenenTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving this file!.
        /// </summary>
        internal static string FoutOpslaanTekst {
            get {
                return ResourceManager.GetString("FoutOpslaanTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string FoutTitel {
            get {
                return ResourceManager.GetString("FoutTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About &quot;SchetsPlus&quot;.
        /// </summary>
        internal static string HelpOver {
            get {
                return ResourceManager.GetString("HelpOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other....
        /// </summary>
        internal static string KiesKleur {
            get {
                return ResourceManager.GetString("KiesKleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen width:.
        /// </summary>
        internal static string LabelPendikte {
            get {
                return ResourceManager.GetString("LabelPendikte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen color:.
        /// </summary>
        internal static string LabelPenkleur {
            get {
                return ResourceManager.GetString("LabelPenkleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Action.
        /// </summary>
        internal static string MenuActie {
            get {
                return ResourceManager.GetString("MenuActie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tool.
        /// </summary>
        internal static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Schets.
        /// </summary>
        internal static string NieuweSchets {
            get {
                return ResourceManager.GetString("NieuweSchets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchetsPlus version 1.0
        ///(c) UU Computer Science 2014.
        /// </summary>
        internal static string OverTekst {
            get {
                return ResourceManager.GetString("OverTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About &quot;SchetsPlus&quot;.
        /// </summary>
        internal static string OverTitel {
            get {
                return ResourceManager.GetString("OverTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schets Files (*.schets)|*.schets.
        /// </summary>
        internal static string SchetsFilter {
            get {
                return ResourceManager.GetString("SchetsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchetsPlus.
        /// </summary>
        internal static string SchetsPlusTitel {
            get {
                return ResourceManager.GetString("SchetsPlusTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ellipse.
        /// </summary>
        internal static string ToolEllipsTekst {
            get {
                return ResourceManager.GetString("ToolEllipsTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eraser.
        /// </summary>
        internal static string ToolGumTekst {
            get {
                return ResourceManager.GetString("ToolGumTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to box.
        /// </summary>
        internal static string ToolKaderTekst {
            get {
                return ResourceManager.GetString("ToolKaderTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to layer.
        /// </summary>
        internal static string ToolLayerTekst {
            get {
                return ResourceManager.GetString("ToolLayerTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to line.
        /// </summary>
        internal static string ToolLijnTekst {
            get {
                return ResourceManager.GetString("ToolLijnTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pen.
        /// </summary>
        internal static string ToolPenTekst {
            get {
                return ResourceManager.GetString("ToolPenTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to picker.
        /// </summary>
        internal static string ToolPipetTekst {
            get {
                return ResourceManager.GetString("ToolPipetTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string ToolTekstTekst {
            get {
                return ResourceManager.GetString("ToolTekstTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flat.
        /// </summary>
        internal static string ToolVlakTekst {
            get {
                return ResourceManager.GetString("ToolVlakTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fillipse.
        /// </summary>
        internal static string ToolVullipsTekst {
            get {
                return ResourceManager.GetString("ToolVullipsTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes?.
        /// </summary>
        internal static string WijzigingenOpslaanTekst {
            get {
                return ResourceManager.GetString("WijzigingenOpslaanTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save?.
        /// </summary>
        internal static string WijzigingenOpslaanTitel {
            get {
                return ResourceManager.GetString("WijzigingenOpslaanTitel", resourceCulture);
            }
        }
    }
}
