//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchetsEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchetsEditor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string ActieClear {
            get {
                return ResourceManager.GetString("ActieClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies &amp;dikte.
        /// </summary>
        internal static string ActieKiesDikte {
            get {
                return ResourceManager.GetString("ActieKiesDikte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies &amp;kleur.
        /// </summary>
        internal static string ActieKiesKleur {
            get {
                return ResourceManager.GetString("ActieKiesKleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R&amp;edo.
        /// </summary>
        internal static string ActieRedo {
            get {
                return ResourceManager.GetString("ActieRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Roteer.
        /// </summary>
        internal static string ActieRoteer {
            get {
                return ResourceManager.GetString("ActieRoteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Undo.
        /// </summary>
        internal static string ActieUndo {
            get {
                return ResourceManager.GetString("ActieUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verander &amp;font.
        /// </summary>
        internal static string ActieVeranderFont {
            get {
                return ResourceManager.GetString("ActieVeranderFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitmap (*.bmp)|*.bmp|JPEG (*.jpg)|*.jpg|PNG (*.png)|*.png.
        /// </summary>
        internal static string ExporterenFilter {
            get {
                return ResourceManager.GetString("ExporterenFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xporteer.
        /// </summary>
        internal static string FileExporteer {
            get {
                return ResourceManager.GetString("FileExporteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Nieuw.
        /// </summary>
        internal static string FileNieuw {
            get {
                return ResourceManager.GetString("FileNieuw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Openen.
        /// </summary>
        internal static string FileOpenen {
            get {
                return ResourceManager.GetString("FileOpenen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op&amp;slaan.
        /// </summary>
        internal static string FileOpslaan {
            get {
                return ResourceManager.GetString("FileOpslaan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan &amp;als....
        /// </summary>
        internal static string FileOpslaanAls {
            get {
                return ResourceManager.GetString("FileOpslaanAls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;luiten.
        /// </summary>
        internal static string FileSluiten {
            get {
                return ResourceManager.GetString("FileSluiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het exporteren!.
        /// </summary>
        internal static string FoutExporterenTekst {
            get {
                return ResourceManager.GetString("FoutExporterenTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het openen van het bestand!.
        /// </summary>
        internal static string FoutOpenenTekst {
            get {
                return ResourceManager.GetString("FoutOpenenTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het opslaan!.
        /// </summary>
        internal static string FoutOpslaanTekst {
            get {
                return ResourceManager.GetString("FoutOpslaanTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout!.
        /// </summary>
        internal static string FoutTitel {
            get {
                return ResourceManager.GetString("FoutTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Over &quot;SchetsPlus&quot;.
        /// </summary>
        internal static string HelpOver {
            get {
                return ResourceManager.GetString("HelpOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anders....
        /// </summary>
        internal static string KiesKleur {
            get {
                return ResourceManager.GetString("KiesKleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendikte:.
        /// </summary>
        internal static string LabelPendikte {
            get {
                return ResourceManager.GetString("LabelPendikte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Penkleur:.
        /// </summary>
        internal static string LabelPenkleur {
            get {
                return ResourceManager.GetString("LabelPenkleur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Actie.
        /// </summary>
        internal static string MenuActie {
            get {
                return ResourceManager.GetString("MenuActie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuHelp {
            get {
                return ResourceManager.GetString("MenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tool.
        /// </summary>
        internal static string MenuTool {
            get {
                return ResourceManager.GetString("MenuTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe Schets.
        /// </summary>
        internal static string NieuweSchets {
            get {
                return ResourceManager.GetString("NieuweSchets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchetsPlus versie 1.0
        ///(c) UU Informatica 2014.
        /// </summary>
        internal static string OverTekst {
            get {
                return ResourceManager.GetString("OverTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over &quot;SchetsPlus&quot;.
        /// </summary>
        internal static string OverTitel {
            get {
                return ResourceManager.GetString("OverTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schets Files (*.schets)|*.schets.
        /// </summary>
        internal static string SchetsFilter {
            get {
                return ResourceManager.GetString("SchetsFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchetsPlus.
        /// </summary>
        internal static string SchetsPlusTitel {
            get {
                return ResourceManager.GetString("SchetsPlusTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ellips.
        /// </summary>
        internal static string ToolEllipsTekst {
            get {
                return ResourceManager.GetString("ToolEllipsTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gum.
        /// </summary>
        internal static string ToolGumTekst {
            get {
                return ResourceManager.GetString("ToolGumTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kader.
        /// </summary>
        internal static string ToolKaderTekst {
            get {
                return ResourceManager.GetString("ToolKaderTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lijn.
        /// </summary>
        internal static string ToolLijnTekst {
            get {
                return ResourceManager.GetString("ToolLijnTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pen.
        /// </summary>
        internal static string ToolPenTekst {
            get {
                return ResourceManager.GetString("ToolPenTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pipet.
        /// </summary>
        internal static string ToolPipetTekst {
            get {
                return ResourceManager.GetString("ToolPipetTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tekst.
        /// </summary>
        internal static string ToolTekstTekst {
            get {
                return ResourceManager.GetString("ToolTekstTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vlak.
        /// </summary>
        internal static string ToolVlakTekst {
            get {
                return ResourceManager.GetString("ToolVlakTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vullips.
        /// </summary>
        internal static string ToolVullipsTekst {
            get {
                return ResourceManager.GetString("ToolVullipsTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wilt u de wijzigingen opslaan?.
        /// </summary>
        internal static string WijzigingenOpslaanTekst {
            get {
                return ResourceManager.GetString("WijzigingenOpslaanTekst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan?.
        /// </summary>
        internal static string WijzigingenOpslaanTitel {
            get {
                return ResourceManager.GetString("WijzigingenOpslaanTitel", resourceCulture);
            }
        }
    }
}
